on: [push]

name: Build Docker images

jobs:
  build_code_maat:
    name: Build 
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build Docker Images
      uses: philips-software/docker-ci-scripts@v4.5.2
      with:
        dockerfile: 1/alpine
        image-name: code-maat
        tags: latest 1 1.0 1.0.2 1.0.2-alpine
      env:
        REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        REGISTRY_TOKEN: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
